DROP TABLE IF EXISTS worker, client, project, project_worker;

CREATE TABLE worker(
        ID INT PRIMARY KEY,
        NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) BETWEEN 2 AND 1000),
        BIRTHDAY DATE CHECK (EXTRACT(YEAR FROM BIRTHDAY) > 1900),
        LEVEL VARCHAR(20) CHECK(LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
        SALARY INT NOT NULL CHECK(SALARY BETWEEN 100 AND 100000)
);

CREATE TABLE client(
        ID INT PRIMARY KEY,
        NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) BETWEEN 2 AND 1000)
);

CREATE TABLE project(
        ID INT PRIMARY KEY,
        CLIENT_ID INT,
        START_DATE DATE,
        FINISH_DATE DATE
);

CREATE TABLE project_worker(
        PROJECT_ID INT,
        WORKER_ID INT,
        PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY(PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
);
